name: build and test
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
env:
  DOTNET_VERSION: '6.0.x'
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      env:
        ASPNETCORE_ENVRINOMENT: Development
      
  super-linter:
    name: Lint Code Base
    if: ${{ !startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Lint Code Base
      id: lintcodebase
      uses: github/super-linter@v4
      continue-on-error: true   
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_JSCPD: false
        VALIDATE_GITHUB_ACTIONS: false
        # Change to 'master' if your main branch differs
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  deploy-development:
    name: Deploy to Development
    needs: [super-linter]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: 
      group: ${{github.repository}}-${{ github.workflow }}-development
      cancel-in-progress: true
    environment:
      name: Development
      url: 'https://www.sampledevelopmenturl.com'
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: print-environment
      run: |
        echo 'Deployed to dev environment.'
   
  deploy-staging:
    name: Deploy to QA
    needs: [deploy-development]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: 
      group: ${{github.repository}}-${{ github.workflow }}-qa
      cancel-in-progress: true
    environment:
      name: QA
      url: 'https://www.sampleqaurl.com'
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: print-environment
      run: |
        echo 'Deployed to QA environment.'
   
  deploy-production:
    name: Deploy to Production
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: 
      group: ${{github.repository}}-${{ github.workflow }}-production
      cancel-in-progress: true
    environment:
      name: Production
      url: 'https://www.sampleproduction.com'
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: print-environment
      run: |
        echo 'Deployed to production environment.'
  
