name: build and test
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
env:
  DOTNET_VERSION: '6.0.x'
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
  sonarcloud:
    name: SAST Scan (SonarCloud)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with: 
           # Disable shallow clones for improved analysis relevency.
           fetch-depth: 0
      - name: Set up dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          distribution: 'microsoft'
      
      # Speed-up analysis by caching the scanner workspace
      - name: Cache SonarCloud workspace
        uses: actions/cache@v1
        with:
          path: ~\.sonar\cache
          key: ${{ runner.os }}-sonar-cache
          restore-keys: ${{ runner.os }}-sonar-cache
          
      # Speed-up analysis by caching the scanner installation
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
          
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner 
      - name: Build
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"devopslabbookproject" /o:"devopslabbookproject" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build ImageTextExtraction.sln
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      
  super-linter:
    name: Lint Code Base
    if: ${{ !startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Lint Code Base
      id: lintcodebase
      uses: github/super-linter@v4
      continue-on-error: true   
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_JSCPD: false
        VALIDATE_GITHUB_ACTIONS: false
        # Change to 'master' if your main branch differs
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  deploy-development:
    name: Deploy to Development
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: 
      group: ${{github.repository}}-${{ github.workflow }}-development
      cancel-in-progress: true
    environment:
      name: Development
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
   
  deploy-staging:
    name: Deploy to QA
    needs: [deploy-development]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: 
      group: ${{github.repository}}-${{ github.workflow }}-qa
      cancel-in-progress: true
    environment:
      name: QA
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
   
  deploy-production:
    name: Deploy to Production
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: 
      group: ${{github.repository}}-${{ github.workflow }}-production
      cancel-in-progress: true
    environment:
      name: Production
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
  
